### PR TITLE
Enable usage in nested addons

### PR DESCRIPTION
**Pull request by pittst3r**
This addresses issue #5.

### CODE REVIEW

**Comment by pittst3r** [comment]
AppVeyor failure is because it [hasn't been finished getting set up](https://github.com/tomdale/ember-network/pull/4).

**Comment by stefanpenner** [comment]
> AppVeyor failure is because it hasn't been finished getting set up.

ya, its not quite ready. It can be ignored for now.

**Comment by stefanpenner** [comment]
I'll look into this PR this weekend (just doing bunch of conf things right now)

**Comment by pittst3r** [comment]
Thanks! No rush.

**Comment by vlascik** [comment]
Any chance this could be merged soon?

**Comment by pwfisher** [comment]
Yes, please merge.

**Comment by pwfisher** [comment]
`app.app` will not work for 3rd level dependencies ember-cli/ember-cli#5747

**Comment by pittst3r** [comment]
@pwfisher What do you think of the changes in my latest commit (f6cb5de)? Takes care of nth level dependencies.

The alternative is making a blueprint in the addon consuming `ember-network` that adds `ember-network` to the `devDependencies` of the host app ([like this](https://github.com/mu-semtech/login-ember-addon/commit/a2da4b8a8758900b18c55c30be129cf0eb689d9e#commitcomment-17174499)).

Which route is better? Leaning towards the latter but not sure. I will defer to @stefanpenner.

**Comment by ef4** [comment]
As of https://github.com/ember-cli/ember-cli/pull/5877 ember-cli no longer requires this class of hack, and there is [a new addon](https://github.com/ember-cli/ember-cli-import-polyfill) that polyfills the behaviors on existing ember-cli releases.

**Comment by pittst3r** [comment]
@ef4 Awesome! Thanks for the heads-up.

**Pull request closed without merging**
